document.write('<html>');
document.write('    <head>');
document.write('        <meta charset=\'UTF-8\'>');
document.write('        <link href=\'/LegianaPage/style1.css\' rel=\'stylesheet\'>');
document.write('        <link rel=\'icon\' href=\'/LegianaPage/Pic/logo.png\' type=\'image/x-icon\'>');
document.write('    </head>');
document.write('    <body>');
document.write('        <section class=\'sec2\'>');
document.write('            <div class=\'animation-area\'>');
document.write('                <ul class=\'box-area\'>');
document.write('                    <li></li>');
document.write('                    <li></li>');
document.write('                    <li></li>');
document.write('                    <li></li>');
document.write('                    <li></li>');
document.write('                    <li></li>');
document.write('                </ul>');
document.write('            </div>');
document.write('        </section>');
document.write('    </body>');
document.write('</html>');