document.writeln("<html>");
document.writeln("    <head>");
document.writeln("        <meta charset=\'UTF-8\'>");
document.writeln("        <link href=\'/HTML\/\/style1.css\' rel=\'stylesheet\'>");
document.writeln("        <link rel=\'icon\' href=\'/HTML\/\/Pic/logo.png\' type=\'image/x-icon\'/>");
document.writeln("    </head>");
document.writeln("    <body>");
document.writeln("    <section class=\'sec2\'>");
document.writeln("        <div class=\'animation-area\'>");
document.writeln("            <ul class=\'box-area\'>");
document.writeln("                <li></li>");
document.writeln("                <li></li>");
document.writeln("                <li></li>");
document.writeln("                <li></li>");
document.writeln("                <li></li>");
document.writeln("                <li></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </section>");
document.writeln("    </body>");
document.writeln("</html>");