document.writeln('<html>');
document.writeln('    <head>');
document.writeln('        <link href=\'/LegianaPage/style1.css\' rel=\'stylesheet\'>');
document.writeln('    </head>');
document.writeln('    <body>');
document.writeln('        <header>');
document.writeln('            <a href=\'/LegianaPage/index.html\'><img src=\'/LegianaPage/Pic/logo.png\' class="logo" width="100" height="100"></a>');
document.writeln('            <ul>');
document.writeln('                <li><a href=\'/LegianaPage/index.html\'>首頁</a></li>');
document.writeln('                <li><a href=\'/LegianaPage/Page/diary.html\'>日記</a></li>');
document.writeln('                <li><a href=\'/LegianaPage/Page/Music.html\'>關於我</a></li>');
document.writeln('            </ul>');
document.writeln('        </header>');
document.writeln('    </body>');
document.writeln('</html>');