document.writeln("<html>");
document.writeln("  <head>");
document.writeln("    <link href=\'/HTML\/\/style1.css\' rel=\'stylesheet\'>");
document.writeln("  </head>");
document.writeln("<body>");
document.writeln("      <header>");
document.writeln("        <a href=\'/HTML\/\/index.html\'><img src=\'/HTML\/\/Pic/logo.png\' class=\'logo\' width=\'100\' height=\'100\'></a>");
document.writeln("        <ul>");
document.writeln("          <li><a href=\'/HTML\/\/index.html\'>首頁</a></li>");
document.writeln("          <li><a href=\'/HTML/Page/diary.html\'>日記</a></li>");
document.writeln("          <li><a href=\'/HTML/Page/Music.html\'>音樂推介</a></li>");
document.writeln("        </ul>");
document.writeln("      </header>");
document.writeln("  </body>");
document.writeln("</html>");