document.write('<html>');
document.write('    <head>');
document.write('        <link href=\'./style1.css\' rel=\'stylesheet\'>');
document.write('    </head>');
document.write('    <body>');
document.write('        <header>');
document.write('            <a href=\'./index.html\'><img src=\'./Pic/logo.png\' class="logo" width="100" height="100"></a>');
document.write('            <ul>');
document.write('                <li><a href=\'./index.html\'>首頁</a></li>');
document.write('                <li><a href=\'./Page/diary.html\'>日記</a></li>');
document.write('                <li><a href=\'/Page/Music.html\'>音樂推介</a></li>');
document.write('            </ul>');
document.write('        </header>');
document.write('    </body>');
document.write('</html>');