document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('  <head>');
document.write('    <link rel="icon" href="../Pic/logo.png" type="image/x-icon"/>');
document.write('    <meta charset="UTF-8">');
document.write('    <title>傷心小棧裏的信心花舍</title>');
document.write('    <script type="text/javascript" src="LegianaPage/header.js"></script>');
document.write('    <script type="text/javascript" src="BacktoTop.js"></script>');
document.write('    <link href="Page.css" rel="stylesheet">');
document.write('  </head>');
document.write('  <body>');
document.write('    <div class="name_blank">');
document.write('      <div class="name">');
document.write('          <h2>傷心小棧裏的信心花舍</h2>');
document.write('      </div>');
document.write('    </div>');
document.write('    <div class="Title">');
document.write('      <div class="new">');
document.write('        <span>');
document.write('            <a href="diary.html">最新日記</a>');
document.write('        </span>');
document.write('      </div>');
document.write('    </div>');
document.write('    <button onclick="topFunction()" id="btt" title="返回地球^^"><img class="btt-img" src=\'/HTML\\Pic/btt.png\' alt=\'\'></button>');
document.write('  </body>');
document.write('</html>');
document.write('');
